FORMAT: 1A
HOST: https://cryptic-badlands-8184.herokuapp.com/

# Life saving API

# Emergency [/112]
Emergency endpoint.

# Call first aid [POST]

+ Request (application/json)

  + Body
    + Attributes
      + emergency: true (boolean, required)

+ Response 201 (application/json; charset=utf-8)

  + Body
    + Attributes (Person)
      
# Data Structures

## Person
- name (string)
- email: z@apiary.io - this is email